---
title: "Business Intelligence & Data Science"
subtitle: "Vorlesung 1"
---


## Example slide

### This is a  sub-title

::: aside
Some additional commentary of more peripheral interest.
:::

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

::: {.notes}
Speaker notes go here.
:::

## Example

### This is another sub-title

```{=html}
 <iframe id="example1" src="https://learnr-examples.shinyapps.io/ex-data-filter/#section-filter-rows-with-filter" style="border: none; width: 100%; height: 720px" frameborder="0"></iframe>
```


## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

::: {.callout-tip}
## Tip with Title

This is an example of a callout with a title.
:::


{{< video https://www.youtube.com/embed/wo9vZccmqwc >}}